<?php

use Illuminate\Database\Seeder;

class postsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $list = [];
        $content = [];

        $user_id = ["1", "1", "1", "1", "1"];
        $title = ["Rò rỉ nhiều thông tin về Galaxy Note 10: 4 camera, chip Snapdragon 855, RAM 12GB", "Xuất hiện hình ảnh render sắc nét của smartphone OPPO zoom quang 10x", "Galalaxy S10 ra mắt tại Việt Nam: Giá tốt hơn dự kiến, chỉ từ 16 triệu", "Với Qualcomm, 5G không chỉ dành cho điện thoại mà còn cả PC", "OPPO trình làng điện thoại gập nhưng sẽ không sản xuất hàng loạt"];
        $image = ["1577094305_post5.jpg", "1577094407_post4.jpg", "1577094465_post3.jpg", "1577094513_post2.jpg", "1577094560_post1.jpg"];
        $content1 = <<<EOT
        <h2 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 0px; margin-bottom: 10px; font-size: 17px; letter-spacing: 0.01em; background-color: #ffffff;">Samsung đã trình làng 4 mẫu smartphone cao cấp trong năm nay, bao gồm: Galaxy S10e, Galaxy S10, Galaxy S10+, Galaxy S10 5G và Galaxy Fold siêu đắt. Tuy nhiên, có ít nhất một chiếc smartphone cao cấp khác mà công ty sẽ ra mắt trong năm 2019.</h2>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Chúng ta đang nói về một chiếc Galaxy Note mới, kế thừa sự thành công của Galaxy Note 9, và đó chính là Galaxy Note 10.</p>
        <h3 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 10px; margin-bottom: 10px; font-size: 1.71429em; letter-spacing: 0.01em; background-color: #ffffff;"><strong style="box-sizing: border-box;">Galaxy Note 10 có 4 camera</strong></h3>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Báo cáo mới nhất tiết lộ Galaxy Note 10 sẽ có 4 camera mặt sau, tăng từ 2 camera trên Galaxy Note 9. Thông tin này đến từ một nguồn đáng tin cậy, nhưng như thường lệ, Samsung vẫn chưa xác nhận. Cho dù thông tin này là chính xác thì chúng ta cũng không quá ngạc nhiên, bởi chiếc Galaxy S10 5G mới ra mắt cũng đã được tích hợp 4 camera mặt sau.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Rò rỉ nhiều thông tin về Galaxy Note 10: 4 camera, chip Snapdragon 855, RAM 12GB" src="https://cdn.tgdd.vn/Files/2019/02/26/1151884/samsung-galaxy-note-10-1_940x627-800-resize.jpg" alt="Rò rỉ nhiều thông tin về Galaxy Note 10: 4 camera, chip Snapdragon 855, RAM 12GB" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151884/samsung-galaxy-note-10-1_940x627-800-resize.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Trên Galaxy S10 5G, 4 camera sau bao gồm: Cảm biến chính 12 MP, camera tele 12 MP (cho zoom quang 2x), camera chụp góc rộng 16 MP và camera 3D Depth (hỗ trợ quét 3D, thực tế ảo tăng cường). Tuy nhiên, Galaxy S10 5G sẽ lên kệ trong vài tháng tới, vì vậy vẫn chưa thể biết được 4 camera trên flagship này hoạt động tốt thế nào. Cũng có khả năng 4 camera trên Note 10 sẽ có cấu hình tương tự, nhưng với một số cải tiến, nâng cấp.</p>
        <h3 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 10px; margin-bottom: 10px; font-size: 1.71429em; letter-spacing: 0.01em; background-color: #ffffff;"><strong style="box-sizing: border-box;">Galaxy Note 10 sẽ có các biến thể 5G và 4G riêng biệt</strong></h3>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Một chi tiết thú vị khác mới được phát hiện gần đây đó là số model của Galaxy Note 10, một trong những model của nó là SM-N975F. Theo truyền thống, số model của Galaxy Note sẽ có kết thúc bằng số “0”, ví dụ như: SM-N960 (Note 9), SM-N950 (Note 8), SM-N930 (Note 7). Vì vậy, SM-N975 có thể là biến thể 5G của Note 10. Tuy nhiên, máy cũng sẽ có phiên bản 4G, có thể với số model là SM-N970.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Rò rỉ nhiều thông tin về Galaxy Note 10: 4 camera, chip Snapdragon 855, RAM 12GB" src="https://cdn.tgdd.vn/Files/2019/02/26/1151884/fa1_1280x720-800-resize.jpg" alt="Rò rỉ nhiều thông tin về Galaxy Note 10: 4 camera, chip Snapdragon 855, RAM 12GB" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151884/fa1_1280x720-800-resize.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Việc có cả phiên bản 4G và 5G rất có ý nghĩa vì mạng 5G chỉ mới bắt đầu được triển khai trong năm nay và sẽ phải mất một vài năm trước khi chúng phổ biến hơn. Đây là lý do vì sao có một phiên bản Galaxy S10 5G khác biệt, trong khi Galaxy S10e, Galaxy S10 và Galaxy S10+ lên kệ trong vài tuần tới đều là các thiết bị 4G.</p>
        <h3 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 10px; margin-bottom: 10px; font-size: 1.71429em; letter-spacing: 0.01em; background-color: #ffffff;"><strong style="box-sizing: border-box;">Các tính năng khác của Galaxy Note 10</strong></h3>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Không chỉ nâng cấp về camera mà Galaxy Note 10 cũng được tin sẽ có nhiều cải tiến khác so với Galaxy Note 9, bao gồm bộ vi xử lý Snapdragon 855 (tương tự như phiên bản Galaxy S10 tại Mỹ), bộ nhớ RAM lên tới 12 GB, ROM 1 TB và bút S Pen nâng cao.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Rò rỉ nhiều thông tin về Galaxy Note 10: 4 camera, chip Snapdragon 855, RAM 12GB" src="https://cdn.tgdd.vn/Files/2019/02/26/1151884/fa-_1920x1080-800-resize.jpg" alt="Rò rỉ nhiều thông tin về Galaxy Note 10: 4 camera, chip Snapdragon 855, RAM 12GB" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151884/fa-_1920x1080-800-resize.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Theo một báo cáo gần đây, Galaxy Note 10 sẽ có màn hình 6.75 inch, là chiếc Galaxy Note lớn nhất từ trước tới nay. Tuy nhiên, nhờ vào màn hình Infinity-O với viền cạnh mỏng mà dự kiến nó cũng có kích thước tương tự như Galaxy Note 9 (màn hình 6.4 inch).</p>
        <h3 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 10px; margin-bottom: 10px; font-size: 1.71429em; letter-spacing: 0.01em; background-color: #ffffff;"><strong style="box-sizing: border-box;">Giá bán và ngày ra mắt của Galaxy Note 10</strong></h3>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Năm ngoái, Galaxy Note 9 đã được ra mắt và lên kệ vào tháng 8, vì vậy Galaxy Note 10 cũng có thể ra mắt vào 1 khung thời gian tương tự trong năm nay.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Đối với smartphone mới này, giá bán cũng sẽ khá cao. Galaxy S10+ với RAM 12 GB + ROM 1 TB được bán ra với giá 1.599 USD (khoảng 37 triệu đồng). Thế nên Galaxy Note 10 với cấu hình tương tự sẽ có giá cao hơn. Mặc dù vậy, hy vọng, Samsung cũng sẽ có một biến thể Note 10 với giá 1.000 USD (khoảng 23.2 triệu đồng), giống với phiên bản Note 9 128 GB năm ngoái.</p>
        EOT;
        $content2 = <<<EOT
        <h2 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 0px; margin-bottom: 10px; font-size: 17px; letter-spacing: 0.01em; background-color: #ffffff;">Chỉ vài ngày trước đây, OPPO đã ra mắt công nghệ zoom quang 10x dành cho smartphone tại MWC 2019. Tại sự kiện này, hãng đã trưng bày 1 nguyên mẫu smartphone áp dụng công nghệ camera này, tuy nhiên nó đã bị che khuất trong 1 bộ ốp bảo vệ.</h2>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Tin vui là bây giờ, một render được cho là smartphone OPPO zoom quang 10x đã được chia sẻ trên trang mạng xã hội Weibo Trung Quốc.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Mặc dù chưa rõ tên gọi của máy nhưng hình ảnh đã cho thấy rõ cả mặt trước và mặt sau của smartphone mới. Ở mặt sau, máy có 3 camera và được đặt theo chiều dọc, bên dưới là đèn flash LED khá nhỏ gọn. Bộ camera này được cho là bao gồm 1 cảm biến chính 48MP, 1 cảm biến góc rộng 120 độ và 1 ống kính tele. Trong hình ảnh, mặt sau của máy bóng bẩy, vì vậy dự kiến mặt sau sẽ được phủ kính.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Xuất hiện hình ảnh render sắc nét của smartphone OPPO zoom quang 10x" src="https://cdn.tgdd.vn/Files/2019/02/26/1151980/oppo-10x-lossless-zoom-camera-1_800x545.jpg" alt="Xuất hiện hình ảnh render sắc nét của smartphone OPPO zoom quang 10x" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151980/oppo-10x-lossless-zoom-camera-1_800x545.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Ở mặt trước, máy có màn hình tràn cạnh và notch tai thỏ giống với iPhone X. Nguồn tin cho rằng trong phần tai thỏ, ngoài camera selfie thì còn có cả module 3D ToF nhận dạng khuôn mặt, loa thoại và cảm biến khác.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Tại MWC 2019, OPPO cho biết hãng sẽ trình làng smartphone hỗ trợ zoom quang 10x vào quý 2/2019. Vì vậy vẫn còn quá sớm để khẳng định rằng render trên sẽ là phiên bản cuối cùng.</p>
        EOT;
        $content3 = <<<EOT
        <h2 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 0px; margin-bottom: 10px; font-size: 17px; letter-spacing: 0.01em; background-color: #ffffff;">Hôm nay (26/2), Samsung đã tổ chức một sự kiện hoành tráng để ra mắt Galaxy S10e, Galaxy S10 và Galaxy S10+ (Galaxy S10 Plus) tại thị trường Việt Nam - một trong những thị trường được mở bán sớm dòng siêu phẩm kỷ niệm 10 năm. Nhìn chung những thiết bị này có giá bán tốt hơn so với dự kiến trước đó.</h2>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Sau một thập kỷ nỗ lực kiến tạo những điều không thể, dòng Galaxy S đã trở thành biểu tượng cho những phát minh di động cao cấp trên toàn thế giới. Galaxy S10 là lời cam kết tiếp theo của chúng tôi dựa trên tinh thần sáng tạo tuyệt vời đó. Ông Suh Kyung Wook – Tổng Giám đốc Công ty Điện tử Samsung Vina chia sẻ.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Galaxy S10" src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/s10-ra-mat-1_800x600.jpg" alt="Galaxy S10" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/s10-ra-mat-1_800x600.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Tại Việt Nam, chúng tôi trao quyền chủ động để người dùng hiện thực hóa tương lai của chính mình thông qua những công nghệ đột phá mà Samsung gửi gắm. Galaxy S10 cung cấp mọi thứ người dùng Việt mong đợi từ dòng Galaxy S, và hơn thế nữa, kiến tạo một chuẩn mực điện thoại thông minh mới cho thập kỷ tiếp theo.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Galaxy S10" src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/3_800x450.jpg" alt="Galaxy S10" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/3_800x450.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Cả bộ ba dòng Galaxy S10e và Galaxy S10 và Galaxy S10+ đều được trang bị màn hình Dynamic AMOLED hoàn toàn mới đầu tiên trên thế giới đầu tiên hỗ trợ HDR10+.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Màn hình này cho độ sáng lên tới 1.200 nit, độ chính xác màu cực cao và tỉ lệ tương phản tốt nhất ở mức 2.000.000:1 và bảo vệ đôi mắt của người sử dụng khi giảm được 42% ánh sáng xanh. Tại thị trường Việt Nam thì bộ 3 sản phẩm này được sử dụng bộ vi xử lý Exynos 9820 8nm do Samsung sản xuất.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Galaxy S10" src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/7_800x450.jpg" alt="Galaxy S10" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/7_800x450.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Galaxy S10e là thiết bị có giá bán rẻ nhất trong số 3 sản phẩm được Samsung trình làng, thiết bị này có màn hình phẳng kích thước 5.8 inch Full HD+ và cảm biến vân tay tích hợp ở cạnh bên. Mặt lưng của máy có cụm camera kép sau bao gồm 12 MP và camera góc siêu rộng 123 độ với độ phân giải 16 MP. Phần "nốt ruồi" ở trong màn hình là nơi đặt camera selfie độ phân giải 10 MP.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Ngoài ra, Galaxy S10e được trang bị hệ thống âm thanh nổi AKG, hỗ trợ Dolby Atmos, viên pin dung lượng 3.100 mAh và thiết bị được phân phối một phiên bản duy nhất tại nước ta là 6 GB RAM và 128 GB bộ nhớ trong.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Galaxy S10" src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/ramats10taivietnam16_800x450.jpg" alt="Galaxy S10" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/ramats10taivietnam16_800x450.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Còn Galaxy S10 và Galaxy S10+ là những phiên bản cao cấp hơn không chỉ được nâng cấp về hệ thống camera so với Galaxy S10e thì bộ đôi này còn có thêm cảm biến vân tay siêu âm dưới màn hình cho tốc độ mở khóa nhanh, hoạt động được dù ngón tay của người dùng bị ướt hay dính dầu mỡ, kem dưỡng da.. và khả năng sạc ngược cho thiết bị khác, chẳng hạn như chính chiếc tai nghe Galaxy Buds.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Galaxy S10" src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/10_800x450.jpg" alt="Galaxy S10" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/10_800x450.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Hai thiết bị này đều hữu hệ thống camera sau bao gồm: camera góc rộng 77° độ phân giải 12 MP thay đổi được khẩu độ giữa F/1.5 và F/2.4, góc siêu rộng 123° độ phân giải 16 MP khẩu độ F/2.2 và camera tele độ phân giải 12 MP khẩu độ F/2.4.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="S10" src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/15_800x450.jpg" alt="S10" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/15_800x450.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Hệ thống này có một số tính năng mới như trình tối ưu hóa cảnh với khả năng nhận diện hơn 30 cảnh khác nhau,  dùng các đề xuất để cải thiện ảnh, tính năng Shot Suggestion cung cấp các mẹo hữu ích để người dùng chụp ảnh đẹp hơn, hỗ trợ quay video HDR10+, xóa phông theo thời gian thực.. và với chế độ Instargram bạn có thể chia sẻ những bức ảnh lên mạng xã hội chỉ với một lần chạm.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Chưa hết, Galaxy S10 và S10+ còn hỗ trợ quay video 4K, có chống rung từ camera selfie, phiên bản Galaxy S10+ cao cấp hơn vì ngoài camera độ phân giải 10 MP như S10 thì nó còn có thêm một camera 8 MP để xóa phông tốt hơn. </p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Galaxy S10" src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/6_800x450.jpg" alt="Galaxy S10" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/6_800x450.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Galaxy S10 sử dụng màn hình Infinity-O kích thước 6.1 inch, viên pin dung lượng 3.400 mAh và S10+ có viên pin khủng hơn với dung lượng 4.100 mAh, kích thước màn hình lớn 6.4 inch. </p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Cuối cùng, cả 3 phiên bản dòng Galaxy S10 đều hỗ trợ chống nước IP68, hỗ trợ kết nối LTE với tốc độ lên tới 2 Gbps, chuẩn Wi-Fi 6 mới hỗ trợ tốc độ lên tới 1.2 Gbps, hệ điều hành Android 9 Pie với giao diện OneUI và cổng cắm tai nghe 3.5 mm.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Galaxy S10" src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/ramats10taivietnam17_800x450.jpg" alt="Galaxy S10" data-src="https://cdn.tgdd.vn/Files/2019/02/26/1151950/ramats10taivietnam17_800x450.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Quan trọng nhất, Samsung còn công bố giá bán cụ thể của Galaxy S10 tại thị trường Việt Nam như sau: Galaxy S10e 6 GB RAM /128 GBROM có giá 15.99 triệu chỉ được bán Online, Galaxy S10 8 GB RAM /128 GB ROM giá 20.99 triệu, Galaxy S10+ 8 GB RAM /128 GB ROM giá 22.99 triệu, 8 GB RAM/512 GB ROM giá 28.99 và phiên bản Galaxy S10+ mặt lưng gốm 12 GB RAM/ 1TB ROM giá 33.99 triệu.</p>
        EOT;
        $content4 = <<<EOT
        <h2 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 0px; margin-bottom: 10px; font-size: 17px; letter-spacing: 0.01em; background-color: #ffffff;">Qualcomm đang có kế hoạch để trở thành nhà sản xuất đầu tiên công bố các PC hỗ trợ 5G bằng hai vũ khí bí mật là modem Snapdragon X55 và bộ xử lý PC Snapdragon 8cx. Tại MWC 2019, chúng ta sẽ có cái nhìn cụ thể hơn về cách mà hai công nghệ kết hợp để tạo ra nền tảng PC hỗ trợ 5G đầu tiên.</h2>
        <h3 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 10px; margin-bottom: 10px; font-size: 1.71429em; letter-spacing: 0.01em; background-color: #ffffff;"><strong style="box-sizing: border-box;">Snapdragon X55 và Snapdragon 8cx</strong></h3>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">So với các PC x86 truyền thống được trang bị chip xử lý Intel hay AMD, “PC luôn kết nối” tập trung phát triển vào thiết kế gọn nhẹ, hiện đại hóa và thời lượng sử dụng lâu hơn. Nhưng sự kết nối luôn là ưu tiên hàng đầu của PC Qualcomm.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Ảnh minh họa" src="https://cdn.tgdd.vn/Files/2019/02/25/1151847/qualcommx55_800x533.jpg" alt="Ảnh minh họa" data-src="https://cdn.tgdd.vn/Files/2019/02/25/1151847/qualcommx55_800x533.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Gần đây, Qualcomm vừa cho ra mắt modem Snapdragon X55, cho phép các thiết bị sử dụng có thể kết nối với 5G, 4G, 3G và thậm chí là 2G trên toàn thế giới. Modem X55 được thiết kế để có thể hoạt động trên nhiều thiết bị khác nhau, từ điện thoại, xe hơi không người lái và cả PC. Tuy X55 có thể ghép nối với PC sử dụng chip Intel hoặc AMD, nhưng nó lại có một sự kết nối đặc biệt với chip xử lý Snapdragon 8cx.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="Ảnh minh họa" src="https://cdn.tgdd.vn/Files/2019/02/25/1151847/qualcomm8cx_800x533.jpg" alt="Ảnh minh họa" data-src="https://cdn.tgdd.vn/Files/2019/02/25/1151847/qualcomm8cx_800x533.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Snapdragon 8cx được thiết kế chạy trên Windows 10 của Microsoft trên một thiết bị hỗ trợ ARM. Khi những PC luôn kết nối trang bị chip 8cx được tích hợp cả modem X55 thì sẽ khiến tốc độ internet trở nên nhanh hơn. Nền tảng PC luôn kết nối này sẽ có thời lượng sử dụng khoảng 20 giờ đồng hồ.</p>
        <h3 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 10px; margin-bottom: 10px; font-size: 1.71429em; letter-spacing: 0.01em; background-color: #ffffff;"><strong style="box-sizing: border-box;">Thay đổi cách người dùng sử dụng PC</strong></h3>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Tốc độ Internet trở nên nhanh hơn thì người dùng sẽ được trải nghiệm 5G dựa trên kho dữ liệu đám mây. Vì 5G có độ trễ thấp và băng thông lớn nên kho dữ liệu đám mây sẽ bắt đầu hoạt động giống như kho lưu trữ trong ổ cứng PC.</p>
        EOT;
        $content5 = <<<EOT
        <h2 style="box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-weight: 500; line-height: 1.4; color: #323c3f; margin-top: 0px; margin-bottom: 10px; font-size: 17px; letter-spacing: 0.01em; background-color: #ffffff;">Thiết bị di động có thể gập (Foldable) đang là cơn sốt trong thị trường điện tử toàn cầu. Không chỉ Samsung và Huawei đều cho ra mắt sản phẩm mới, ngay cả OPPOcũng đã cho lộ diện siêu phẩm của riêng mình với giới truyền thông.</h2>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><iframe class=" lazied" style="box-sizing: border-box; max-width: 100%; margin: 0px auto; display: block;" src="https://www.youtube.com/embed/O6eDVyo8Thw" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Với sự ra mắt của siêu phẩm Galaxy Fold của Samsung, nó đã tạo nên cơn sốt toàn cầu, tác động vô cùng mạnh mẽ đến các nhà sản xuất thiết bị điện tử và người tiêu dùng. Tiếp đến là sản phẩm di động với thiết kế vô cùng độc đáo Mate X đến từ Huawei, với sức ảnh hưởng cũng không hề kém cạnh. Có lẽ rằng các nhà sản xuất điện thoại đang muốn tạo ra một để chế mới, với những thiết kế mới lạ và chưa từng có.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="màn hình gập OPPO" src="https://cdn.tgdd.vn/Files/2019/02/25/1151821/a1_690x388.jpg" alt="màn hình gập OPPO" data-src="https://cdn.tgdd.vn/Files/2019/02/25/1151821/a1_690x388.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Có thể chắc chắn rằng ở thời điểm ra mắt sản phẩm, người dùng sẽ không thể nhanh chóng tiếp cận đến chúng, nhưng tin rằng chỉ trong vòng vài tháng nữa người tiêu dùng sẽ "chạm" vào dòng sản phẩm foldable này.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Với Samsung và Huawei, họ đều là những nhà sản xuất thiết bị điện tử nổi tiếng và đây là thời điểm quan trọng khi họ sẵn sàng thử vận may với dòng sản phẩm này trên thị trường.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Trong khi đó, các nhà sản xuất Trung Quốc khác vẫn đang nỗ lực, làm việc chăm chỉ để có thể hoàn thiện các dòng điện thoại gập. Với công ty Xiaomi, sản phẩm gập vẫn còn ở giai đoạn nguyên mẫu và họ đang rất cố gắng để sẵn sàng cạnh tranh với các thương hiệu di động khác.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="màn hình gập OPPO" src="https://cdn.tgdd.vn/Files/2019/02/25/1151821/a2_690x541.jpg" alt="màn hình gập OPPO" data-src="https://cdn.tgdd.vn/Files/2019/02/25/1151821/a2_690x541.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Còn với OPPO, hãng cũng đã tiết lộ với giới truyền thông một vài hình ảnh thực sự của chiếc điện thoại thông minh OPPO có thể gập lại vô cùng ấn tượng, nhưng Phó Chủ tịch của hãng cũng nói rằng công ty không có kế hoạch nào cho việc sản xuất hàng loạt.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Nhìn vào bức ảnh, chiếc điện thoại thông minh OPPO có thiết kế tương tự như Mate X của Huawei. Theo đánh giá về phản ứng của người dùng khi cho ra mắt Mate X của Huawei, kết quả thu được là sự thích thú vô cùng bởi thiết kế khác biệt hoàn toàn với những dòng sản phẩm trước.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;"><img class=" lazied" style="box-sizing: border-box; border: 0px none; vertical-align: middle; max-width: 100%; height: auto !important; margin: 0px auto; display: block;" title="màn hình gập OPPO" src="https://cdn.tgdd.vn/Files/2019/02/25/1151821/007a578zgy1g0ijpy5arpj34mo334qv9_690x388.jpg" alt="màn hình gập OPPO" data-src="https://cdn.tgdd.vn/Files/2019/02/25/1151821/007a578zgy1g0ijpy5arpj34mo334qv9_690x388.jpg"></p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Với kết quả này, chắc chắn rằng mẫu thiết kế này sẽ được các nhà sản xuất khác theo đuổi kịch liệt. Giới truyền thông đã thật sự rất ngạc nhiên khi sếp của OPPO lên tiếng rằng công ty không có một kế hoạch cho việc sản xuất sản phẩm hàng loạt.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 15px; color: #363f4d; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; letter-spacing: 0.25px; background-color: #ffffff;">Theo các nhà phân tích, công nghệ điện thoại gập này đang rất mới mẻ và khá là non trẻ. Nếu thiết bị gập có thể được sản xuất hàng loạt, chắc chắn rằng doanh thu sẽ tăng lên rất nhiều với cái giá "cắt cổ". Với thị trường tiêu thụ rộng lớn, sản phẩm độc lạ và đầy ấn tượng, chắc chắn OPPO sẽ thu về cho mình khoản doanh thu không hề nhỏ một chút nào.</p>
        EOT;
        array_push($content, $content1, $content2, $content3, $content4, $content5);
       
        $created_at = ["2019-12-23 16:45:05", "2019-12-23 16:46:47", "2019-12-23 16:47:45", "2019-12-23 16:48:33", "2019-12-23 16:49:20"];
        $updated_at = ["2019-12-23 16:45:05", "2019-12-23 16:46:47", "2019-12-23 16:47:45", "2019-12-23 16:48:33", "2019-12-23 16:49:20"];
        for ($i=1; $i <= count($user_id); $i++) {
            array_push($list, [
                'id'                        => $i,
                'user_id'                   => $user_id[$i-1],
                'title'                     => $title[$i-1],
                'image'                     => $image[$i-1],
                'content'                   => $content[$i-1],
                'created_at'                => $created_at[$i-1],
                'updated_at'                => $updated_at[$i-1],
            ]);
        }
        DB::table('posts')->insert($list);
    }
}
